const courses = [
    { code: "BECE102L", title: "Digital Systems Design" },
    { code: "BECE102P", title: "Digital Systems Design Lab" },
    { code: "BECE201L", title: "Electronic Materials and Devices" },
    { code: "BECE202L", title: "Signals and Systems" },
    { code: "BECE203L", title: "Circuit Theory" },
    { code: "BECE204L", title: "Microprocessors and Microcontrollers" },
    { code: "BECE204P", title: "Microprocessors and Microcontrollers Lab" },
    { code: "BECE205L", title: "Engineering Electromagnetics" },
    { code: "BECE206L", title: "Analog Circuits" },
    { code: "BECE206P", title: "Analog Circuits Lab" },
    { code: "BECE207L", title: "Random Processes" },
    { code: "BECE208E", title: "Data Structures and Algorithms" },
    { code: "BECE209E", title: "Structured and Object Oriented Programming" },
    { code: "BECE301L", title: "Digital Signal Processing" },
    { code: "BECE301P", title: "Digital Signal Processing Lab" },
    { code: "BECE302L", title: "Control Systems" },
    { code: "BECE303L", title: "VLSI System Design" },
    { code: "BECE303P", title: "VLSI System Design Lab" },
    { code: "BECE304L", title: "Analog Communication Systems" },
    { code: "BECE304P", title: "Analog Communication Systems Lab" },
    { code: "BECE305L", title: "Antenna and Microwave Engineering" },
    { code: "BECE305P", title: "Antenna and Microwave Engineering Lab" },
    { code: "BECE306L", title: "Digital Communication Systems" },
    { code: "BECE306P", title: "Digital Communication Systems Lab" },
    { code: "BECE307L", title: "Wireless and Mobile Communications" },
    { code: "BECE307P", title: "Wireless and Mobile Communications Lab" },
    { code: "BECE308L", title: "Optical Fiber Communications" },
    { code: "BECE308P", title: "Optical Fiber Communications Lab" },
    { code: "BECE309L", title: "Artificial Intelligence and Machine Learning" },
    { code: "BECE310L", title: "Satellite Communications" },
    { code: "BECE312L", title: "Robotics and Automation" },
    { code: "BECE313L", title: "Information Theory and Coding" },
    { code: "BECE401L", title: "Computer Communications and Networks" },
    { code: "BECE401P", title: "Computer Communications and Networks Lab" },
    { code: "BECE406E", title: "FPGA Based System Design" },
    { code: "BECE407E", title: "ASIC Design" },
    { code: "BECE409E", title: "Sensors Technology" },
    { code: "CFOC191M", title: "Forest and their Management" },
    { code: "CFOC575M", title: "Wildlife Ecology" },
    { code: "BCHY101L", title: "Engineering Chemistry" },
    { code: "BCHY102N", title: "Environmental Science" },
    { code: "BENG101L", title: "Technical English Communication" },
    { code: "BENG102P", title: "Technical Report Writing" },
    { code: "BCSE101E", title: "Computer Programming Python" },
    { code: "BCSE102L", title: "Structured and Object Oriented Programming" },
    { code: "BCSE103E", title: "Computer Programming Java" },
    { code: "BCSE202L", title: "Data Structures and Algorithms" },
    { code: "BCSE202P", title: "Data Structures and Algorithms Lab" },
    { code: "BCSE204L", title: "Design and Analysis of Algorithm" },
    { code: "BCSE205L", title: "Computer Architecture and Organization" },
    { code: "BCSE209L", title: "Machine Learning" },
    { code: "BCSE301L", title: "Software Engineering" },
    { code: "BCSE302L", title: "Database Systems" },
    { code: "BCSE302P", title: "Database Systems Lab" },
    { code: "BCSE303L", title: "Operating Systems" },
    { code: "BCSE303P", title: "Operating Systems Lab" },
    { code: "BCSE304L", title: "Theory of Computation" },
    { code: "BCSE305L", title: "Embedded Systems" },
    { code: "BCSE306L", title: "Artificial Intelligence" },
    { code: "BCSE307L", title: "Compiler Design" },
    { code: "BCSE308L", title: "Computer Networks" },
    { code: "BCSE308P", title: "Computer Networks Lab" },
    { code: "BCSE309L", title: "Cryptography and Network Security" },
    { code: "BCSE316L", title: "Design of Smart Cities" },
    { code: "BCSE332L", title: "Deep Learning" },
    { code: "BCSE351E", title: "Foundations of Data Analytics" },
    { code: "BCSE353E", title: "Information Security Analysis and Audit" },
    { code: "BCSE355L", title: "AWS Solutions Architect" },
    { code: "BCSE403L", title: "Digital Image Processing" },
    { code: "BCSE404L", title: "Internet and Web Programming" },
    { code: "BCSE409L", title: "Natural Language Processing" },
    { code: "BCSE412L", title: "Parallel Computing" },
    { code: "BCSE415L", title: "Human Computer Interaction" },
    { code: "BCSE420L", title: "Sensors, Actuators and Signal Conditioning" },
    { code: "BEEE102L", title: "Basic Electrical and Electronics Engineering" },
    { code: "BEEE201L", title: "Electronic Materials" },
    { code: "BEEE202L", title: "Signals and Systems" },
    { code: "BEEE203L", title: "Circuit Theory" },
    { code: "BEEE206L", title: "Digital Electronics" },
    { code: "BEEE303L", title: "Control Systems" },
    { code: "BEEE305L", title: "Measurements and Instrumentation" },
    { code: "BESP101L", title: "Spanish I" },
    { code: "BFRE101L", title: "French I" },
    { code: "BGER101L", title: "German I" },
    { code: "BJAP101L", title: "Japanese I" },
    { code: "BMAT101L", title: "Calculus" },
    { code: "BMAT101P", title: "Calculus Lab" },
    { code: "BMAT102L", title: "Differential Equations and Transforms" },
    { code: "BMAT201L", title: "Complex Variables and Linear Algebra" },
    { code: "BMAT202L", title: "Probability and Statistics" },
    { code: "BMAT202P", title: "Probability and Statistics Lab" },
    { code: "BMAT205L", title: "Discrete Mathematics and Graph Theory" },
    { code: "BMEE102P", title: "Engineering Design Visualization Lab" },
    { code: "BMEE201L", title: "Engineering Mechanics" },
    { code: "BMEE202L", title: "Mechanics of Solids" },
    { code: "BMEE203L", title: "Engineering Thermodynamics" },
    { code: "BMEE204L", title: "Fluid Mechanics and Machines" },
    { code: "BMEE207L", title: "Kinematics and Dynamics of Machines" },
    { code: "BMEE208L", title: "Industrial Engineering" },
    { code: "BMEE209L", title: "Material Science and Engineering" },
    { code: "BMEE210L", title: "Mechatronics and Measurements System" },
    { code: "BMEE211L", title: "Engineering Optimization" },
    { code: "BMEE301L", title: "Design of Machine Elements" },
    { code: "BMEE302L", title: "Metal Casting and Welding" },
    { code: "BMEE302P", title: "Metal Casting and Welding Lab" },
    { code: "BMEE303L", title: "Thermal Engineering Systems" },
    { code: "BMEE304L", title: "Metal Forming and Machining" },
    { code: "BMEE306L", title: "Computer Aided Design and Finite Element Analysis" },
    { code: "BMEE313E", title: "Non-destructive Testing" },
    { code: "BMEE402L", title: "Heat and Mass Transfer" },
    { code: "BMEE403L", title: "Design of Jigs, Fixtures and Press Tools" },
    { code: "BMEE404L", title: "Design of Transmission Systems" },
    { code: "BECM301L", title: "Signal Processing" },
    { code: "BPHY101L", title: "Engineering Physics" },
    { code: "BPHY101P", title: "Engineering Physics Lab" },
    { code: "BMEE310L", title: "Supply Chain Management" },
    { code: "BMEE325L", title: "Internal Combustion Engine" },
    { code: "BMEE326L", title: "Power Plant Engineering" },
    { code: "BMEE407L", title: "Artificial Intelligence" },
    { code: "BMEE409E", title: "Computational Fluid Dynamics" },
    { code: "BMEE411L", title: "Society 5.0" },
    { code: "BCLE203L", title: "Mechanics of Solids" },
    { code: "BMGT103L", title: "Organizational Behaviour" }
];