const courses = [
    { code: "BECE102L", title: "Digital Systems Design" },
    { code: "BECE102P", title: "Digital Systems Design Lab" },
    { code: "BECE201L", title: "Electronic Materials and Devices" },
    { code: "BECE202L", title: "Signals and Systems" },
    { code: "BECE203L", title: "Circuit Theory" },
    { code: "BECE204L", title: "Microprocessors and Microcontrollers" },
    { code: "BECE204P", title: "Microprocessors and Microcontrollers Lab" },
    { code: "BECE205L", title: "Engineering Electromagnetics" },
    { code: "BECE206L", title: "Analog Circuits" },
    { code: "BECE206P", title: "Analog Circuits Lab" },
    { code: "BECE207L", title: "Random Processes" },
    { code: "BECE208E", title: "Data Structures and Algorithms" },
    { code: "BECE209E", title: "Structured and Object Oriented Programming" },
    { code: "BECE301L", title: "Digital Signal Processing" },
    { code: "BECE301P", title: "Digital Signal Processing Lab" },
    { code: "BECE302L", title: "Control Systems" },
    { code: "BECE303L", title: "VLSI System Design" },
    { code: "BECE303P", title: "VLSI System Design Lab" },
    { code: "BECE304L", title: "Analog Communication Systems" },
    { code: "BECE304P", title: "Analog Communication Systems Lab" },
    { code: "BECE305L", title: "Antenna and Microwave Engineering" },
    { code: "BECE305P", title: "Antenna and Microwave Engineering Lab" },
    { code: "BECE306L", title: "Digital Communication Systems" },
    { code: "BECE306P", title: "Digital Communication Systems Lab" },
    { code: "BECE307L", title: "Wireless and Mobile Communications" },
    { code: "BECE307P", title: "Wireless and Mobile Communications Lab" },
    { code: "BECE308L", title: "Optical Fiber Communications" },
    { code: "BECE308P", title: "Optical Fiber Communications Lab" },
    { code: "BECE309L", title: "Artificial Intelligence and Machine Learning" },
    { code: "BECE310L", title: "Satellite Communications" },
    { code: "BECE312L", title: "Robotics and Automation" },
    { code: "BECE313L", title: "Information Theory and Coding" },
    { code: "BECE401L", title: "Computer Communications and Networks" },
    { code: "BECE401P", title: "Computer Communications and Networks Lab" },
    { code: "BECE406E", title: "FPGA Based System Design" },
    { code: "BECE407E", title: "ASIC Design" },
    { code: "BECE409E", title: "Sensors Technology" },
    { code: "CFOC191M", title: "Forest and their Management" },
    { code: "CFOC575M", title: "Wildlife Ecology" },
    { code: "BCHY101L", title: "Engineering Chemistry" },
    { code: "BCHY102N", title: "Environmental Science" },
    { code: "BENG101L", title: "Technical English Communication" },
    { code: "BENG102P", title: "Technical Report Writing" }
];